"""empty message

Revision ID: 803e7b79f3ad
Revises: 
Create Date: 2026-03-19 17:42:27.916093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '803e7b79f3ad'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roots',
    sa.Column('tree_id', sa.Integer(), nullable=False),
    sa.Column('soil_id', sa.Integer(), nullable=False),
    sa.Column('a', sa.Float(), nullable=False),
    sa.Column('b', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('soils',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('soil_c', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trees',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('center_gravity_height', sa.Float(), nullable=False),
    sa.Column('diameter', sa.Float(), nullable=False),
    sa.Column('c_d', sa.Float(), nullable=False),
    sa.Column('crown_square', sa.Float(), nullable=False),
    sa.Column('max_stress', sa.Float(), nullable=False),
    sa.Column('type_root', sa.String(), nullable=False),
    sa.Column('info', sa.String(), nullable=False),
    sa.Column('is_new', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trees')
    op.drop_table('soils')
    op.drop_table('roots')
    # ### end Alembic commands ###
