"""create base

Revision ID: 0f3dc9656116
Revises: 
Create Date: 2026-03-10 22:48:52.807655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f3dc9656116'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Roots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_tree', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Soils',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('soil_c', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Trees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('center_gravity_height', sa.Float(), nullable=False),
    sa.Column('diameter', sa.Float(), nullable=False),
    sa.Column('c_d', sa.Float(), nullable=False),
    sa.Column('crown_square', sa.Float(), nullable=False),
    sa.Column('info', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Trees')
    op.drop_table('Soils')
    op.drop_table('Roots')
    # ### end Alembic commands ###
