"""Edit4

Revision ID: 12a126ef904b
Revises: 4258848fa3a0
Create Date: 2026-03-10 23:36:47.824193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12a126ef904b'
down_revision: Union[str, Sequence[str], None] = '4258848fa3a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Roots', sa.Column('type_soil', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Roots', 'type_soil')
    # ### end Alembic commands ###
