"""Edit3

Revision ID: 4258848fa3a0
Revises: a69a69d2e3a8
Create Date: 2026-03-10 23:33:22.064066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4258848fa3a0'
down_revision: Union[str, Sequence[str], None] = 'a69a69d2e3a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('Roots', sa.Column('type_soil', sa.String()))
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
