"""Edit

Revision ID: 5970bf588ada
Revises: 0f3dc9656116
Create Date: 2026-03-10 23:09:47.736957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5970bf588ada'
down_revision: Union[str, Sequence[str], None] = '0f3dc9656116'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Roots', sa.Column('a', sa.Integer(), nullable=True))
    op.add_column('Roots', sa.Column('b', sa.Integer(), nullable=True))
    op.add_column('Trees', sa.Column('type_root', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Trees', 'type_root')
    op.drop_column('Roots', 'b')
    op.drop_column('Roots', 'a')
    # ### end Alembic commands ###
